version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: zenshespa_database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
      - ./backend/.env.docker
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app:ro

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://rightly-wise-tadpole.ngrok-free.app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
